Update deploy-pg-api.yml

diff --git a/.github/workflows/deploy-pg-api.yml b/.github/workflows/deploy-pg-api.yml
--- a/.github/workflows/deploy-pg-api.yml
+++ b/.github/workflows/deploy-pg-api.yml
@@ -13,17 +13,29 @@ jobs:
         with:
           node-version: 20
 
-      - run: echo 'hello world ...'
-      - run: ls -la
-      - run: touch .env
-      - run: echo "DEV_DATABASE_URL=${{ secrets.PG_CONN }}" >> .env
-      - run: cat .env
+      # Crear archivo .env con la variable de conexión a la base de datos
+      - name: Configurar archivo .env
+        run: |
+          touch .env
+          echo "DEV_DATABASE_URL=${{ secrets.PG_CONN }}" >> .env
+          cat .env
 
-      - run: docker build -t adsoft/pg-restapi:${{ github.sha }} .
-      - run: docker images
+      # Construir imagen Docker
+      - name: Construir imagen Docker
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pg-restapi:${{ github.sha }} .
 
+      # Verificar credenciales de Docker
+      - name: 🚨 Verificar credenciales de Docker
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "Error: Las credenciales DOCKER_USERNAME o DOCKER_PASSWORD no están configuradas."
+            exit 1
+          fi
+
+      # Iniciar sesión en Docker Hub
       - name: 🔑 Iniciar sesión en Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      - name: 🚀 Subir imagen a Docker Hub
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/pg-restapi:${{ github.sha }}
+      # Subir imagen a Docker Hub
+      - name: 🚀 Sub](#)
+
